### ISSUE TITLE
how to trigger an instant backup?

### ISSUE THREAD

**Issue by seertenedos** [djmaze/resticker#16]
Is there a way to run a backup right now via docker compose instead of on a timer?

i tried
`docker-compose run --rm app backup`
but it just told me there were no files to backup where i have mapped files though

**Comment by djmaze** [comment]
That does not work because `backup` is taken as an argument to `restic` in this case (as opposed to running the `backup` script). 

1. If you have the app container already running (via `docker-compose up -d`) you can use 
    ```bash
    docker-compose exec app backup
    ```
2. Alternatively, you can override the entrypoint during `run`:
    ```bash
    docker-compose run --entrypoint bash app backup
    ```

Both not tested, but should work.

**Comment by seertenedos** [comment]
Thanks that should work for my use cases
