### ISSUE TITLE
latest-tag does not represent the latest release

### ISSUE THREAD

**Issue by dasBuero** [djmaze/resticker#24]
If you pull the docker image without a tag (`mazzolino/restic`) or with `latest`, you get a much older release of resticker. By default docker should pull the latest release.

**Comment by djmaze** [comment]
Sorry for that. As I am all for semantic versioning, I would rather not have a `latest` tag *at all*. It is better to use the `1` or `1.1` tags in order to be sure not to get any breaking changes when pulling the image again.

That said, I am not sure how to best document the current version (and I don't want to step on people's toes), so for now the latest `master` changes will be pushed under the `latest` image tag.

**Comment by dasBuero** [comment]
Thank you for resolving this issue!
I'm also for semantic versioning in order to avoid unintended consequences, especially with backup tools.
Maybe the following tag schema makes sense:
`master` or `dev` > master branch
`latest` > latest release
