### ISSUE TITLE
PRE_COMMANDS: Invalid interpolation format for "environment" option in service

### ISSUE THREAD

**Issue by Altiano** [djmaze/resticker#31]
Why this value won't work?
```
PRE_COMMANDS: |-
            docker stop reverse_proxy
            docker stop $(docker ps | grep blogcomments | awk '{print $1}') 
            docker stop $(docker ps | grep mailcowdockerized | awk '{print $1}') 
```

**Comment by djmaze** [comment]
So what exactly is the error message? Is it an error given by docker-compose during parsing?

**Comment by Altiano** [comment]
The error message: PRE_COMMANDS: Invalid interpolation format for "environment" option in service

**Comment by djmaze** [comment]
Ah, right, I see ;)

Well, using advanced shell syntax in the `PRE_COMMANDS` or `POST_COMMANDS` variable probably won't work because it is just `eval`ed inside the main script. I suggest putting those lines into a separate script file, mount that into the container and then just call the script in the `PRE_COMMANDS`.

**Comment by alexmisk** [comment]
Hеу! Sorry for necroposting, but I've just faced almost the same issue.

Try to double the `$` sign in your PRE_COMMANDS like this:

```
PRE_COMMANDS: |-
            docker stop reverse_proxy
            docker stop $$(docker ps | grep blogcomments | awk '{print $$1}') 
            docker stop $$(docker ps | grep mailcowdockerized | awk '{print $$1}') 
```
